// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Book struct {
	ID     int64
	Title  sql.NullString
	Price  sql.NullString
	Author sql.NullString
}
